In [2]:
import numpy as np
import pandas as pd

scores=np.random.randint(50, 101, size=(50,5))
scores_pd = pd.DataFrame(scores,columns=['國文', '英文', '數學', '地理', '歷史'],index=range(1,51))
scores_pd.index.name = "學號"
scores_pd.columns.name = "科目"
scores_pd

科目  國文  英文   數學  地理  歷史
學號
1   74  94   79  67  68
2   57  86   99  99  86
3   80  70   66  73  89
4   79  60   98  92  87
5   80  93   79  88  60
6   78  68   52  85  76
7   52  52   94  72  90
8   74  84   80  72  81
9   93  57   70  73  65
10  81  83   54  98  68
11  60  51   91  63  63
12  57  84   88  57  60
13  86  73   89  70  93
14  84  80   89  74  89
15  74  55   67  85  97
16  92  79   90  98  98
17  93  57   69  69  89
18  84  73   93  54  84
19  91  97   60  74  64
20  57  64   95  61  67
21  98  58   62  89  60
22  70  72   99  67  87
23  52  95  100  82  82
24  63  78   61  66  58
25  79  95   94  85  98
26  89  64   58  58  98
27  96  78   71  69  81
28  88  79   98  71  98
29  59  93   69  70  52
30  95  74   92  63  72
31  73  59   62  96  88
32  63  83   78  55  98
33  81  84   95  58  57
34  96  88   70  63  71
35  89  93   86  64  97
36  91  67   82  77  61
37  61  62   87  84  63
38  61  64   84  51  84
39  74  96  100  63  79
40  91  61   80  98  57
41  96  94   76  75  92
42  75  77   56  52  91
43  68  82   97  77  62
44  67  55   59  69  59
45  70  55   69  90  87
46  73  91   66  79  79
47  79  59   52  61  92
48  82  80   87  76  99
49  51  54   73  61  55
50  65  53   75  87  61

In [5]:
scores_pd['國文']

學號
1     74
2     57
3     80
4     79
5     80
6     78
7     52
8     74
9     93
10    81
11    60
12    57
13    86
14    84
15    74
16    92
17    93
18    84
19    91
20    57
21    98
22    70
23    52
24    63
25    79
26    89
27    96
28    88
29    59
30    95
31    73
32    63
33    81
34    96
35    89
36    91
37    61
38    61
39    74
40    91
41    96
42    75
43    68
44    67
45    70
46    73
47    79
48    82
49    51
50    65
Name: 國文, dtype: int32

In [7]:
scores_pd[['國文','數學']]

科目  國文   數學
學號
1   74   79
2   57   99
3   80   66
4   79   98
5   80   79
6   78   52
7   52   94
8   74   80
9   93   70
10  81   54
11  60   91
12  57   88
13  86   89
14  84   89
15  74   67
16  92   90
17  93   69
18  84   93
19  91   60
20  57   95
21  98   62
22  70   99
23  52  100
24  63   61
25  79   94
26  89   58
27  96   71
28  88   98
29  59   69
30  95   92
31  73   62
32  63   78
33  81   95
34  96   70
35  89   86
36  91   82
37  61   87
38  61   84
39  74  100
40  91   80
41  96   76
42  75   56
43  68   97
44  67   59
45  70   69
46  73   66
47  79   52
48  82   87
49  51   73
50  65   75

In [9]:
scores_pd.reindex(['國文','英文'],axis=1)

科目  國文  英文
學號
1   74  94
2   57  86
3   80  70
4   79  60
5   80  93
6   78  68
7   52  52
8   74  84
9   93  57
10  81  83
11  60  51
12  57  84
13  86  73
14  84  80
15  74  55
16  92  79
17  93  57
18  84  73
19  91  97
20  57  64
21  98  58
22  70  72
23  52  95
24  63  78
25  79  95
26  89  64
27  96  78
28  88  79
29  59  93
30  95  74
31  73  59
32  63  83
33  81  84
34  96  88
35  89  93
36  91  67
37  61  62
38  61  64
39  74  96
40  91  61
41  96  94
42  75  77
43  68  82
44  67  55
45  70  55
46  73  91
47  79  59
48  82  80
49  51  54
50  65  53

In [11]:
scores_pd[:5]

科目  國文  英文  數學  地理  歷史
學號
1   74  94  79  67  68
2   57  86  99  99  86
3   80  70  66  73  89
4   79  60  98  92  87
5   80  93  79  88  60

In [14]:
scores_pd.reindex([1,2,3,4,5])

科目  國文  英文  數學  地理  歷史
學號
1   74  94  79  67  68
2   57  86  99  99  86
3   80  70  66  73  89
4   79  60  98  92  87
5   80  93  79  88  60

In [16]:
scores_pd.iloc[:5]

科目  國文  英文  數學  地理  歷史
學號
1   74  94  79  67  68
2   57  86  99  99  86
3   80  70  66  73  89
4   79  60  98  92  87
5   80  93  79  88  60

In [18]:
scores_pd.reindex(index=[1,2,3,4,5],columns=['國文','數學','歷史'])

科目  國文  數學  歷史
學號
1   74  79  68
2   57  99  86
3   80  66  89
4   79  98  87
5   80  79  60

In [20]:
scores_pd.loc[1:5,['國文','數學','歷史']]

科目  國文  數學  歷史
學號
1   74  79  68
2   57  99  86
3   80  66  89
4   79  98  87
5   80  79  60

In [22]:
scores_pd.iloc[:5,[0,2,4]]

科目  國文  數學  歷史
學號
1   74  79  68
2   57  99  86
3   80  66  89
4   79  98  87
5   80  79  60

In [24]:
scores_pd.iloc[0,0] = 60
scores_pd

科目  國文  英文   數學  地理  歷史
學號
1   60  94   79  67  68
2   57  86   99  99  86
3   80  70   66  73  89
4   79  60   98  92  87
5   80  93   79  88  60
6   78  68   52  85  76
7   52  52   94  72  90
8   74  84   80  72  81
9   93  57   70  73  65
10  81  83   54  98  68
11  60  51   91  63  63
12  57  84   88  57  60
13  86  73   89  70  93
14  84  80   89  74  89
15  74  55   67  85  97
16  92  79   90  98  98
17  93  57   69  69  89
18  84  73   93  54  84
19  91  97   60  74  64
20  57  64   95  61  67
21  98  58   62  89  60
22  70  72   99  67  87
23  52  95  100  82  82
24  63  78   61  66  58
25  79  95   94  85  98
26  89  64   58  58  98
27  96  78   71  69  81
28  88  79   98  71  98
29  59  93   69  70  52
30  95  74   92  63  72
31  73  59   62  96  88
32  63  83   78  55  98
33  81  84   95  58  57
34  96  88   70  63  71
35  89  93   86  64  97
36  91  67   82  77  61
37  61  62   87  84  63
38  61  64   84  51  84
39  74  96  100  63  79
40  91  61   80  98  57
41  96  94   76  75  92
42  75  77   56  52  91
43  68  82   97  77  62
44  67  55   59  69  59
45  70  55   69  90  87
46  73  91   66  79  79
47  79  59   52  61  92
48  82  80   87  76  99
49  51  54   73  61  55
50  65  53   75  87  61

In [26]:
scores_pd.loc[2] = [100,100,100,100,100]
scores_pd.loc[1] = scores_pd.loc[1] + 1
scores_pd.iloc[-3:] -= 5
scores_pd

科目   國文   英文   數學   地理   歷史
學號
1    62   96   81   69   70
2   100  100  100  100  100
3    80   70   66   73   89
4    79   60   98   92   87
5    80   93   79   88   60
6    78   68   52   85   76
7    52   52   94   72   90
8    74   84   80   72   81
9    93   57   70   73   65
10   81   83   54   98   68
11   60   51   91   63   63
12   57   84   88   57   60
13   86   73   89   70   93
14   84   80   89   74   89
15   74   55   67   85   97
16   92   79   90   98   98
17   93   57   69   69   89
18   84   73   93   54   84
19   91   97   60   74   64
20   57   64   95   61   67
21   98   58   62   89   60
22   70   72   99   67   87
23   52   95  100   82   82
24   63   78   61   66   58
25   79   95   94   85   98
26   89   64   58   58   98
27   96   78   71   69   81
28   88   79   98   71   98
29   59   93   69   70   52
30   95   74   92   63   72
31   73   59   62   96   88
32   63   83   78   55   98
33   81   84   95   58   57
34   96   88   70   63   71
35   89   93   86   64   97
36   91   67   82   77   61
37   61   62   87   84   63
38   61   64   84   51   84
39   74   96  100   63   79
40   91   61   80   98   57
41   96   94   76   75   92
42   75   77   56   52   91
43   68   82   97   77   62
44   67   55   59   69   59
45   70   55   69   90   87
46   73   91   66   79   79
47   79   59   52   61   92
48   72   70   77   66   89
49   41   44   63   51   45
50   55   43   65   77   51

In [29]:
#統計
scores_sum=scores_pd.sum(axis=1)

In [31]:
scores_mean = scores_pd.mean(axis=1)
scores_mean

學號
1      75.6
2     100.0
3      75.6
4      83.2
5      80.0
6      71.8
7      72.0
8      78.2
9      71.6
10     76.8
11     65.6
12     69.2
13     82.2
14     83.2
15     75.6
16     91.4
17     75.4
18     77.6
19     77.2
20     68.8
21     73.4
22     79.0
23     82.2
24     65.2
25     90.2
26     73.4
27     79.0
28     86.8
29     68.6
30     79.2
31     75.6
32     75.4
33     75.0
34     77.6
35     85.8
36     75.6
37     71.4
38     68.8
39     82.4
40     77.4
41     86.6
42     70.2
43     77.2
44     61.8
45     74.2
46     77.6
47     68.6
48     74.8
49     48.8
50     58.2
dtype: float64

In [33]:
scores_pd['總分'] = scores_sum
scores_pd['平均'] = scores_mean
scores_pd

科目   國文   英文   數學   地理   歷史   總分     平均
學號
1    62   96   81   69   70  378   75.6
2   100  100  100  100  100  500  100.0
3    80   70   66   73   89  378   75.6
4    79   60   98   92   87  416   83.2
5    80   93   79   88   60  400   80.0
6    78   68   52   85   76  359   71.8
7    52   52   94   72   90  360   72.0
8    74   84   80   72   81  391   78.2
9    93   57   70   73   65  358   71.6
10   81   83   54   98   68  384   76.8
11   60   51   91   63   63  328   65.6
12   57   84   88   57   60  346   69.2
13   86   73   89   70   93  411   82.2
14   84   80   89   74   89  416   83.2
15   74   55   67   85   97  378   75.6
16   92   79   90   98   98  457   91.4
17   93   57   69   69   89  377   75.4
18   84   73   93   54   84  388   77.6
19   91   97   60   74   64  386   77.2
20   57   64   95   61   67  344   68.8
21   98   58   62   89   60  367   73.4
22   70   72   99   67   87  395   79.0
23   52   95  100   82   82  411   82.2
24   63   78   61   66   58  326   65.2
25   79   95   94   85   98  451   90.2
26   89   64   58   58   98  367   73.4
27   96   78   71   69   81  395   79.0
28   88   79   98   71   98  434   86.8
29   59   93   69   70   52  343   68.6
30   95   74   92   63   72  396   79.2
31   73   59   62   96   88  378   75.6
32   63   83   78   55   98  377   75.4
33   81   84   95   58   57  375   75.0
34   96   88   70   63   71  388   77.6
35   89   93   86   64   97  429   85.8
36   91   67   82   77   61  378   75.6
37   61   62   87   84   63  357   71.4
38   61   64   84   51   84  344   68.8
39   74   96  100   63   79  412   82.4
40   91   61   80   98   57  387   77.4
41   96   94   76   75   92  433   86.6
42   75   77   56   52   91  351   70.2
43   68   82   97   77   62  386   77.2
44   67   55   59   69   59  309   61.8
45   70   55   69   90   87  371   74.2
46   73   91   66   79   79  388   77.6
47   79   59   52   61   92  343   68.6
48   72   70   77   66   89  374   74.8
49   41   44   63   51   45  244   48.8
50   55   43   65   77   51  291   58.2

In [35]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [37]:
obj.rank(method='first',ascending=False).astype(int)

0    1
1    7
2    2
3    3
4    5
5    6
6    4
dtype: int32

In [39]:
scores_pd['名次'] = scores_sum.rank(method='first',ascending=False).astype(int)

In [41]:
scores_pd

科目   國文   英文   數學   地理   歷史   總分     平均  名次
學號
1    62   96   81   69   70  378   75.6  24
2   100  100  100  100  100  500  100.0   1
3    80   70   66   73   89  378   75.6  25
4    79   60   98   92   87  416   83.2   7
5    80   93   79   88   60  400   80.0  12
6    78   68   52   85   76  359   71.8  37
7    52   52   94   72   90  360   72.0  36
8    74   84   80   72   81  391   78.2  16
9    93   57   70   73   65  358   71.6  38
10   81   83   54   98   68  384   76.8  23
11   60   51   91   63   63  328   65.6  46
12   57   84   88   57   60  346   69.2  41
13   86   73   89   70   93  411   82.2  10
14   84   80   89   74   89  416   83.2   8
15   74   55   67   85   97  378   75.6  26
16   92   79   90   98   98  457   91.4   2
17   93   57   69   69   89  377   75.4  29
18   84   73   93   54   84  388   77.6  17
19   91   97   60   74   64  386   77.2  21
20   57   64   95   61   67  344   68.8  42
21   98   58   62   89   60  367   73.4  34
22   70   72   99   67   87  395   79.0  14
23   52   95  100   82   82  411   82.2  11
24   63   78   61   66   58  326   65.2  47
25   79   95   94   85   98  451   90.2   3
26   89   64   58   58   98  367   73.4  35
27   96   78   71   69   81  395   79.0  15
28   88   79   98   71   98  434   86.8   4
29   59   93   69   70   52  343   68.6  44
30   95   74   92   63   72  396   79.2  13
31   73   59   62   96   88  378   75.6  27
32   63   83   78   55   98  377   75.4  30
33   81   84   95   58   57  375   75.0  31
34   96   88   70   63   71  388   77.6  18
35   89   93   86   64   97  429   85.8   6
36   91   67   82   77   61  378   75.6  28
37   61   62   87   84   63  357   71.4  39
38   61   64   84   51   84  344   68.8  43
39   74   96  100   63   79  412   82.4   9
40   91   61   80   98   57  387   77.4  20
41   96   94   76   75   92  433   86.6   5
42   75   77   56   52   91  351   70.2  40
43   68   82   97   77   62  386   77.2  22
44   67   55   59   69   59  309   61.8  48
45   70   55   69   90   87  371   74.2  33
46   73   91   66   79   79  388   77.6  19
47   79   59   52   61   92  343   68.6  45
48   72   70   77   66   89  374   74.8  32
49   41   44   63   51   45  244   48.8  50
50   55   43   65   77   51  291   58.2  49

In [43]:
scores_pd.sort_values(by='名次')

科目   國文   英文   數學   地理   歷史   總分     平均  名次
學號
2   100  100  100  100  100  500  100.0   1
16   92   79   90   98   98  457   91.4   2
25   79   95   94   85   98  451   90.2   3
28   88   79   98   71   98  434   86.8   4
41   96   94   76   75   92  433   86.6   5
35   89   93   86   64   97  429   85.8   6
4    79   60   98   92   87  416   83.2   7
14   84   80   89   74   89  416   83.2   8
39   74   96  100   63   79  412   82.4   9
13   86   73   89   70   93  411   82.2  10
23   52   95  100   82   82  411   82.2  11
5    80   93   79   88   60  400   80.0  12
30   95   74   92   63   72  396   79.2  13
22   70   72   99   67   87  395   79.0  14
27   96   78   71   69   81  395   79.0  15
8    74   84   80   72   81  391   78.2  16
18   84   73   93   54   84  388   77.6  17
34   96   88   70   63   71  388   77.6  18
46   73   91   66   79   79  388   77.6  19
40   91   61   80   98   57  387   77.4  20
19   91   97   60   74   64  386   77.2  21
43   68   82   97   77   62  386   77.2  22
10   81   83   54   98   68  384   76.8  23
1    62   96   81   69   70  378   75.6  24
3    80   70   66   73   89  378   75.6  25
15   74   55   67   85   97  378   75.6  26
31   73   59   62   96   88  378   75.6  27
36   91   67   82   77   61  378   75.6  28
17   93   57   69   69   89  377   75.4  29
32   63   83   78   55   98  377   75.4  30
33   81   84   95   58   57  375   75.0  31
48   72   70   77   66   89  374   74.8  32
45   70   55   69   90   87  371   74.2  33
21   98   58   62   89   60  367   73.4  34
26   89   64   58   58   98  367   73.4  35
7    52   52   94   72   90  360   72.0  36
6    78   68   52   85   76  359   71.8  37
9    93   57   70   73   65  358   71.6  38
37   61   62   87   84   63  357   71.4  39
42   75   77   56   52   91  351   70.2  40
12   57   84   88   57   60  346   69.2  41
20   57   64   95   61   67  344   68.8  42
38   61   64   84   51   84  344   68.8  43
29   59   93   69   70   52  343   68.6  44
47   79   59   52   61   92  343   68.6  45
11   60   51   91   63   63  328   65.6  46
24   63   78   61   66   58  326   65.2  47
44   67   55   59   69   59  309   61.8  48
50   55   43   65   77   51  291   58.2  49
49   41   44   63   51   45  244   48.8  50

In [44]:
import numpy as np
import pandas as pd

scores=np.random.randint(50, 101, size=(50,5))
scores_pd = pd.DataFrame(scores,columns=['國文', '英文', '數學', '地理', '歷史'],index=range(1,51))
scores_pd.index.name = "學號"
scores_pd.columns.name = "科目"
scores_sum=scores_pd.sum(axis=1)
scores_mean = scores_pd.mean(axis=1)
scores_pd['總分'] = scores_sum
scores_pd['平均'] = scores_mean
scores_pd['名次'] = scores_sum.rank(method='first',ascending=False).astype(int)
scores_pd.sort_values(by='名次')

科目   國文   英文  數學   地理   歷史   總分    平均  名次
學號
5    80   90  92   96   95  453  90.6   1
41   85   88  90   95   94  452  90.4   2
37   90   91  84   92   91  448  89.6   3
15  100   97  84   81   76  438  87.6   4
16   62   97  76   97   92  424  84.8   5
48   75   85  97   89   72  418  83.6   6
14   98   79  58   91   90  416  83.2   7
1   100   69  86   63   97  415  83.0   8
35   85   92  74   73   90  414  82.8   9
34   97   80  92   62   80  411  82.2  10
49   82   76  98  100   53  409  81.8  11
24   93   66  64   86   99  408  81.6  12
36   79   81  94   58   95  407  81.4  13
47   67   56  97   87  100  407  81.4  14
39   87   97  85   83   50  402  80.4  15
28   65   87  97   92   60  401  80.2  16
4    95   65  95   82   62  399  79.8  17
44   84  100  79   80   52  395  79.0  18
27   63   70  97   66   97  393  78.6  19
18   78   86  69   59  100  392  78.4  20
10   80   62  67   82  100  391  78.2  21
45   69   92  77   50  100  388  77.6  22
2    59   68  67   94   99  387  77.4  23
30   97   85  69   69   66  386  77.2  24
19   59   56  85   87   98  385  77.0  25
9    66   98  54   70   94  382  76.4  26
31   99   78  71   79   54  381  76.2  27
7    92   57  53   85   91  378  75.6  28
21   81   53  89   95   58  376  75.2  29
40   73   66  98   82   54  373  74.6  30
50   62   95  54   94   68  373  74.6  31
46   71   73  66   76   86  372  74.4  32
26   71   95  50   75   79  370  74.0  33
17   71   63  63   83   87  367  73.4  34
20   88   64  55   69   90  366  73.2  35
33   57   79  73   59   98  366  73.2  36
29   86   52  99   56   72  365  73.0  37
6    80   77  82   64   61  364  72.8  38
43   62   83  85   51   76  357  71.4  39
11   72   93  78   59   54  356  71.2  40
38   67   54  98   61   66  346  69.2  41
12   61   84  61   85   54  345  69.0  42
22   98   56  86   50   55  345  69.0  43
23   54   74  58   84   70  340  68.0  44
32   53   82  87   63   54  339  67.8  45
42   95   63  67   54   57  336  67.2  46
3    58   60  76   85   51  330  66.0  47
8    53   61  80   64   72  330  66.0  48
25   64   57  50   67   82  320  64.0  49
13   62   69  64   57   56  308  61.6  50